CREATE TABLE stock(
	id_stock INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	total_product INT NOT NULL,
	last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	product_id INT NOT NULL,
	
	FOREIGN KEY (product_id) REFERENCES products(id_product) ON DELETE CASCADE
);